[package]
name = "vitrellogy"
version = "0.1.0"
authors = ["TechnoElf <jhjavadev@gmail.com>"]
edition = "2018"

[dependencies]
invader = { git = "https://github.com/technoelf/invader" }

sdl2 = { version = "0.34.2", default-features = false, features = ["image", "ttf", "mixer"] }

